- name: bronze
  value: 100
- name: bronze
  value: 250
- name: bronze
  value: 750
- name: silver
  value: 1250
- name: silver
  value: 2000
- name: silver
  value: 3250
- name: gold
  value: 5250
- name: gold
  value: 8500
- name: gold
  value: 13750
- name: platinum
  value: 22250
